services:
  - type: web
    name: ocorrencias-master-app
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_ENV
        value: production 