services:
  - type: web
    name: ocorrencias-master-app
    env: node
    buildCommand: npm run build
    startCommand: npx serve dist -s
    envVars:
      - key: NODE_ENV
        value: production 