services:
  - type: web
    name: ocorrencias-master-app
    buildCommand: npm run render-build
    startCommand: npx serve -s build -l $PORT --config serve.json
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_BASE_URL
        value: https://processador-relatorios-ia.onrender.com
      - key: PORT
        value: 10000
    # Configurações de segurança e HTTPS
    plan: starter
    region: oregon
    # Forçar HTTPS e configurações de segurança
    forceHttps: true
    # Headers de segurança
    headers:
      - key: Strict-Transport-Security
        value: "max-age=31536000; includeSubDomains; preload"
      - key: X-Content-Type-Options
        value: "nosniff"
      - key: X-Frame-Options
        value: "DENY"
      - key: X-XSS-Protection
        value: "1; mode=block"
      - key: Referrer-Policy
        value: "strict-origin-when-cross-origin"
      - key: Permissions-Policy
        value: "camera=(), microphone=(), geolocation=()"
    # Configurações de build e deploy
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - tsconfig.json
        - render.yaml
        - serve.json
    # Configurações de rede e segurança
    healthCheckPath: /
    autoDeploy: true
    # Configurações de cache e performance
    buildCache:
      maxAge: 86400
    # Configurações de logs
    logRetention:
      maxAge: 604800 