import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
    container: {
        padding: 20,
        backgroundColor: '#003c3c', // fundo verde escuro
        flexGrow: 1,
    },
    header: {
        backgroundColor: 'transparent',
        alignItems: 'center',
        marginBottom: 0,
    },
    headerTitle: {
        display: 'none', // título só no AppBar
    },
    subTitle: {
        fontSize: 16,
        color: '#ddd',
        textAlign: 'center',
        marginBottom: 20,
    },
    formContainer: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 3,
    },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 22, // mais espaçamento
    },
    iconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F0F0F0', // Fundo cinza claro para o círculo do ícone
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    icon: {
        color: '#ddd',
        opacity: 0.8,
        marginBottom: 6,
    },
    inputGroupFlex: {
        flex: 1,
    },
    label: {
        color: '#ddd',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 5,
    },
    input: {
        backgroundColor: '#F9F9F9', // Fundo mais claro para os inputs
        color: '#333',
        fontSize: 16,
        borderRadius: 10, // Bordas mais arredondadas
        paddingVertical: 12,
        paddingHorizontal: 15,
        borderWidth: 1,
        borderColor: '#E0E0E0', // Borda sutil
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.03,
        shadowRadius: 2,
        elevation: 1,
    },
    multilineInput: {
        minHeight: 140,
        textAlignVertical: 'top',
        backgroundColor: '#eef5f5',
        borderColor: '#88c0b8',
        borderWidth: 1.5,
    },
    sugestoesBox: {
        backgroundColor: '#fff',
        borderRadius: 8,
        marginTop: 5,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        maxHeight: 150,
        overflow: 'scroll',
        zIndex: 10,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
    },
    sugestaoItem: {
        paddingVertical: 10,
        paddingHorizontal: 15,
        fontSize: 15,
        color: '#333',
        borderBottomWidth: 1,
        borderBottomColor: '#F5F5F5',
    },
    pickerBox: {
        backgroundColor: '#F9F9F9',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.03,
        shadowRadius: 2,
        elevation: 1,
    },
    picker: {
        width: '100%',
        height: 50, // Ajustado para ser mais consistente com os inputs
        color: '#333',
    },
    buttonContainer: {
        marginTop: 25,
        alignItems: 'center',
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        gap: 10,
    },
    analyzeButton: {
        backgroundColor: '#009688',
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 6,
        flex: 2,
    },
    clearButton: {
        backgroundColor: '#f5f5f5',
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderWidth: 1,
        borderColor: '#ddd',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
        flex: 1,
    },
    clearButtonText: {
        color: '#666',
        fontWeight: '600',
        fontSize: 14,
    },
    resultBox: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        marginTop: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
    },
    resultTitle: {
        color: '#111',
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 15,
        textAlign: 'center',
    },
    resultText: {
        color: '#333',
        fontSize: 16,
        fontWeight: '400',
        lineHeight: 24,
        marginBottom: 20,
    },
    resultButtons: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 10,
    },
    resultButton: {
        flex: 1,
        marginHorizontal: 5,
        backgroundColor: colors.secondaryBg || '#4CAF50', // Cor para os botões de ação do resultado
        borderRadius: 10,
        paddingVertical: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    creditoBox: {
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 10,
    },
    creditoText: {
        color: '#ccc',
        fontSize: 13,
        fontStyle: 'italic',
        textAlign: 'center',
        marginTop: 10,
    },
    // Removendo estilos não utilizados ou que não se encaixam no novo layout
    topoBox: { display: 'none' },
    institucionalBox: { display: 'none' },
    logoImg: { display: 'none' },
    institucionalMsg: { display: 'none' },
    bold: { display: 'none' },
    master: { display: 'none' },
    rowInputs: { display: 'none' }, // Este estilo foi substituído por inputRow
    acaoBox: { display: 'none' },
    acaoBtn: { display: 'none' },
}); 